### PR TITLE
Bratseth/shorter twitter

### PR DESCRIPTION
**Pull request by bratseth**
@frodelu or @kkraune please review

This text broke into an extra line. I don't want to get into the layout so just making it shorter  :-)

Btw, what do you feel about having the twitter link in the top header. I want to follow things I'm interested in there because it is the only push mechanism I keep up with in addition to mail. But maybe that's just me?

### CODE REVIEW

**Comment by kkraune** [comment]
@twitter is better yes, and I favor putting it in the top header

**Comment by bratseth** [comment]
Thanks. I will try to send a PR with twitter to Frode then so we are sure to get his opinion.

**Comment by frodelu** [comment]
Why not just say "Twitter" as link text? Why do we need to show "@vespaengine"?

**Comment by bratseth** [comment]
Yes, ok. I shall a pull request create.

**Pull request merged**
