### PR TITLE
Constrain live upgrade guarantee to 2 months

### PR DESCRIPTION
**Pull request by bratseth**

### CODE REVIEW

**Review by frodelu — APPROVED** [review]

**Review by baldersheim — APPROVED** [review]
👍

**Comment by baldersheim** [comment]
@vekterli and @geirst PR

**Review by geirst — APPROVED** [review]
👍

**Review by kkraune — APPROVED** [review]
👍

**Review by vekterli — APPROVED** [review]

**Comment by kkraune** [comment]
@bratseth  good to merge?

**Comment by bratseth** [comment]
yes, thanks

**Pull request merged**
