### PR TITLE
suggested new features

### PR DESCRIPTION
**Pull request by kkraune**
@bratseth @frodelu @johans1  I suggest these 4 features, but open to suggestions - lets get started working on this

### CODE REVIEW

**Comment by frodelu** [comment]
Don't understand why we want to slim it down to only four features? We don't have only four features. I think we are already making it hard enough to understand what Vespa.

Also - with this change, we'd need to rethink the UI for this section. Doesn't make sense to make it this text heavy and use these icons:
image

**Comment by bratseth** [comment]
Enig i at det blir litt mye tekst med det der .. men den som er der er heller ikke så bra. Foreslår:

Search and filtering
Combine structured queries and text search to select data for processing and responses

Advanced ranking
Deploy ML models, from dot products to deep neural nets for ranking and recommendation

Organize and aggregate
Group and aggregate all data matching queries, in real time

Realtime
UI friendly response times, instant writes at high volume

Pluggable
Deploy your own Java components to implement custom logic

Scalable and fast
Optimized for thousands of queries per second and billions of documents

Elastic and fault tolerant
Add, remove and replace machines without losing data

Easy to operate
Configure multi-cluster systems with a few lines of config - change config and code while serving


... vi kan alltids matche dem til de ikonene som står der, akkurat det tror jeg ikke trenger gi mening.

**Comment by kkraune** [comment]
all right, will make new proposal based on Jon's 8 - much better than original - and the icons don't match anyway but looks great!

**Comment by kkraune** [comment]
the pages linked to, (particularly row 1) need some TLC but will get to it or change to something else. The "Read more" looks a bit lame, can be replaced with clicking on icons. otoh, "Read more" is a call to action, maybe keep it. merging for next iteration!

**Comment by kkraune** [comment]
and btw, must match icons to text better, but some fit better than others ... maybe we need a new set given the text ...

**Pull request merged**
